### ISSUE TITLE
Replay Buffer

### ISSUE THREAD

**Issue by fyouly** [CN-UPB/DeepCoMP#15]
Dear author,
May I ask if DeepCoMP centralized DQN has a replay buffer in it or not?
BR

**Comment by stefanbschneider** [comment]
Hi @fyouly , no, it does not use a replay buffer. All versions of DeepCoMP (centralized and distributed) use PPO, not DQN. PPO is an on-policy, rather than off-policy, algorithm, which does not use a replay buffer.

**Comment by stefanbschneider** [comment]
I'm closing this issue for now. Feel free to reopen, if you have more questions.
